---
- hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: add hostname.local entry for loopback
    lineinfile:
      path: /etc/hosts
      regex: "^127.0.0.1"
      create: yes
      line: "127.0.0.1 {{ ansible_hostname }} {{ ansible_hostname }}.local"
  - name: Add necessary hosts to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      create: yes
    with_items:
      - "192.168.5.11 master-1"
      - "192.168.5.12 master-2"
      - "192.168.5.21 worker-1"
      - "192.168.5.22 worker-2"
      - "192.168.5.30 lb"
  - name: install resolvconf
    apt:
      name: resolvconf
  - name: update DNS config
    lineinfile:
      path: "/etc/resolvconf/resolv.conf.d/head"
      line: "{{ item }}"
      create: yes
    loop:
      - "nameserver 8.8.8.8"
      - "nameserver 8.8.4.4"
  - name: restart resolvconf
    service:
      name: resolvconf
      state: restarted
      enabled: yes
  - name: install necessary packages {{ required_packages }}
    apt:
      name: "{{ item }}"
    loop: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - pass
  - name: Add an apt key for docker-ce (debian)
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  - name: get release name
    command: lsb_release -cs
    register: release_name
  - name: add docker repository to apt (debian)
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ release_name.stdout }} stable"
      state: present
  - name: install docker packages
    apt:
      name: "{{ item }}"
    loop: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - name: set net.bridge.bridge-nf-call-iptables=1
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: '1'
      state: present