---
- hosts: master-*
  become: yes
  gather_facts: true
  tasks:
  - name: import common node provision tasks
    import_tasks: provision-node-tasks.yml
  - name: create .ssh directory for vagrant user
    file:
      state: directory
      path: "/home/vagrant/.ssh"
  - name: copy vagrant ssh private key to master for access to all nodes
    copy:
      src: "~/.vagrant.d/insecure_private_key"
      dest: "/home/vagrant/.ssh/id_rsa"
