---
- hosts: master-*
  become: yes
  gather_facts: true
  tasks:
  - name: add hostname.local entry for loopback
    lineinfile:
      path: /etc/hosts
      regex: "^127.0.0.1"
      create: yes
      line: "127.0.0.1 {{ ansible_hostname }} {{ ansible_hostname }}.local"
  - name: Add necessary hosts to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      create: yes
    with_items:
      - "192.168.5.11 master-1"
      - "192.168.5.12 master-2"
      - "192.168.5.21 worker-1"
      - "192.168.5.22 worker-2"
      - "192.168.5.30 lb"
  - name: install resolvconf
    apt:
      name: resolvconf
  - name: update DNS config
    lineinfile:
      path: "/etc/resolvconf/resolv.conf.d/head"
      line: "{{ item }}"
      create: yes
    loop:
      - "nameserver 8.8.8.8"
      - "nameserver 8.8.4.4"
  - name: restart resolvconf
    service:
      name: resolvconf
      state: restarted
      enabled: yes
  - name: create .ssh directory for vagrant user
    file:
      state: directory
      path: "/home/vagrant/.ssh"
  - name: copy vagrant ssh private key to master for access to all nodes
    copy:
      src: "~/.vagrant.d/insecure_private_key"
      dest: "/home/vagrant/.ssh/id_rsa"
  - name: Add the br_netfilter module
    modprobe:
      name: br_netfilter
      state: present
  - name: copy k8s.conf to /etc/sysctl.d/k8s.conf
    copy:
      src: "k8s.conf"
      dest: "/etc/sysctl.d/k8s.conf"
  - name: reload sysctl
    command: sysctl --system
  - name: install apt-transport-https and curl
    apt:
      name:
        - apt-transport-https
        - curl
  - name: Add an apt key for apt.kubernetes.io (debian)
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  - name: add docker apt.kubernetes.io to apt (debian)
    apt_repository:
      repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
      state: present
  - name: install kubelet kubeadm and kubectl
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      update_cache: yes
  - name: pin the kubelet kubeadm and kubectl versions
    command: apt-mark hold kubelet kubeadm kubectl
