---
- hosts: loadbalancer
  become: yes
  gather_facts: true
  tasks:
  - name: add hostname.local entry for loopback
    lineinfile:
      path: /etc/hosts
      regex: "^127.0.0.1"
      create: yes
      line: "127.0.0.1 {{ ansible_hostname }} {{ ansible_hostname }}.local"
  - name: Add necessary hosts to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      create: yes
    with_items:
      - "192.168.5.11 master-1"
      - "192.168.5.12 master-2"
      - "192.168.5.21 worker-1"
      - "192.168.5.22 worker-2"
      - "192.168.5.30 lb"
  - name: install resolvconf
    apt:
      name: resolvconf
  - name: update DNS config
    lineinfile:
      path: "/etc/resolvconf/resolv.conf.d/head"
      line: "{{ item }}"
      create: yes
    loop:
      - "nameserver 8.8.8.8"
      - "nameserver 8.8.4.4"
  - name: restart resolvconf
    service:
      name: resolvconf
      state: restarted
      enabled: yes
  - name: install haproxy
    apt:
      name: haproxy
  - name: copy haproxy config to remote
    copy:
      src: "haproxy.cfg"
      dest: "/etc/haproxy/haproxy.cfg"
  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
      enabled: yes